/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5/userguide/multi_project_builds.html
 */

rootProject.name = "KotlinSpigotPlugin"
include("project")
include("project-1.18")
include("project-1.17")
include("project-1.16")
include("project-1.15")
include("project-1.14")
include("project-1.13")
include("project-1.12")
include("project-1.11")
include("project-1.10")
include("project-1.9")
include("project-1.8")