/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.metumortis.kotlinspigotplugin

class Main {
    var greeting: String = ""
        get() = "Hello World!"
        set(value) {
            field = value
        }

}

