/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.metumortis.kotlinspigotplugin

import org.bukkit.plugin.java.JavaPlugin

class Main : JavaPlugin() {
    override fun onEnable() {
        TODO("Plugin startup logic")
    }

    override fun onDisable() {
        TODO("Plugin shutdown logic")
    }
}



